name: Release
on:
  push:
    branches:
      - main
# GitHub flow: whenever main branch is merged, new release is ready
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          # we already tested with --frozen-lockfile on next when creating pr, now we need to fix bumped pkg by changeset
          run_install: |
            args: [--no-frozen-lockfile]
      - run: node scripts/check-changeset.mjs
      - run: git push
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      # test, build, add meta fields, perform additional checks and finally publish
      - run: pnpx -y zardoy-release pnpm-monorepo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpx -y tsm scripts/update-changeset-branch.ts main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
